name: Terraform Infrastructure

on:
  push:
    branches:
      - dev
      - prod
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

  pull_request:
    branches:
      - dev
      - prod
    paths:
      - "terraform/**"

  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - destroy
      environment:
        description: "Target Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env-setup
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "ENV_NAME=${{ github.base_ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
            echo "ENV_NAME=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "ENV_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials using manually created OIDC role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_INFRA_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -backend-config="${{ env.ENV_NAME }}.tfbackend"

      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        if: github.event_name == 'pull_request' || github.event.inputs.action == 'plan'
        run: terraform plan -var-file="${{ env.ENV_NAME }}.tfvars"

      - name: Terraform apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -var-file="${{ env.ENV_NAME }}.tfvars"

      - name: Show Terraform Outputs
        run: terraform output

      - name: Terraform destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var-file="${{ env.ENV_NAME }}.tfvars"